title: Cayla Celis
logo: CaylaCelis_Headshot.png
description: "Mechanical Engineer | UVA Alum \nB.S., Mechanical Engineering | The University of Virginia (_May 2025_)"
#Mechanical Engineer | UVA Alum
theme: jekyll-theme-minimal
