title: Cayla Celis
logo: CaylaCelis_Headshot.png
description: Mechanical Engineer | UVA Alum
#Mechanical Engineer | UVA Alum
#B.S., Mechanical Engineering | The University of Virginia (_May 2025_)
theme: jekyll-theme-minimal


